# Generated by Django 2.2 on 2021-03-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='books',
            new_name='books_authored_by',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='users',
            new_name='users_who_like',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='users',
            new_name='users_who_like',
        ),
        migrations.RenameField(
            model_name='publishers',
            old_name='books',
            new_name='books_published_by',
        ),
        migrations.RenameField(
            model_name='publishers',
            old_name='users',
            new_name='users_who_like',
        ),
    ]
